# Common unit base forms
UNIT_BASES = {
    # --- Mass ---
    'g': 'gram',
    'gram': 'gram',
    'grams': 'gram',
    'kg': 'kilogram',
    'kilogram': 'kilogram',
    'kilograms': 'kilogram',
    'mg': 'milligram',
    'milligram': 'milligram',
    'milligrams': 'milligram',
    'µg': 'microgram',
    'microgram': 'microgram',
    'micrograms': 'microgram',
    'lb': 'pound',
    'lbs': 'pound',
    'pound': 'pound',
    'pounds': 'pound',
    'oz': 'ounce',
    'ounce': 'ounce',
    'ounces': 'ounce',
    'ton': 'ton',
    'tons': 'ton',
    'tonne': 'ton',
    'tonnes': 'ton',

    # --- Length / Distance ---
    'm': 'meter',
    'meter': 'meter',
    'meters': 'meter',
    'metre': 'meter',
    'metres': 'meter',
    'cm': 'centimeter',
    'centimeter': 'centimeter',
    'centimeters': 'centimeter',
    'mm': 'millimeter',
    'millimeter': 'millimeter',
    'millimeters': 'millimeter',
    'km': 'kilometer',
    'kilometer': 'kilometer',
    'kilometers': 'kilometer',
    'in': 'inch',
    'inch': 'inch',
    'inches': 'inch',
    'ft': 'foot',
    'foot': 'foot',
    'feet': 'foot',
    'yd': 'yard',
    'yard': 'yard',
    'yards': 'yard',
    'mi': 'mile',
    'mile': 'mile',
    'miles': 'mile',
    'nm': 'nautical_mile',
    'nautical_mile': 'nautical_mile',
    'nautical_miles': 'nautical_mile',

    # --- Volume ---
    'l': 'liter',
    'liter': 'liter',
    'liters': 'liter',
    'litre': 'liter',
    'litres': 'liter',
    'ml': 'milliliter',
    'milliliter': 'milliliter',
    'milliliters': 'milliliter',
    'gallon': 'gallon',
    'gallons': 'gallon',
    'qt': 'quart',
    'quart': 'quart',
    'quarts': 'quart',
    'pt': 'pint',
    'pint': 'pint',
    'pints': 'pint',
    'cup': 'cup',
    'cups': 'cup',
    'tbsp': 'tablespoon',
    'tablespoon': 'tablespoon',
    'tablespoons': 'tablespoon',
    'tsp': 'teaspoon',
    'teaspoon': 'teaspoon',
    'teaspoons': 'teaspoon',

    # --- Time ---
    's': 'second',
    'sec': 'second',
    'secs': 'second',
    'second': 'second',
    'seconds': 'second',
    'min': 'minute',
    'mins': 'minute',
    'minute': 'minute',
    'minutes': 'minute',
    'h': 'hour',
    'hr': 'hour',
    'hrs': 'hour',
    'hour': 'hour',
    'hours': 'hour',
    'd': 'day',
    'day': 'day',
    'days': 'day',
    'wk': 'week',
    'wks': 'week',
    'week': 'week',
    'weeks': 'week',
    'mo': 'month',
    'month': 'month',
    'months': 'month',
    'yr': 'year',
    'yrs': 'year',
    'year': 'year',
    'years': 'year',

    # --- Temperature ---
    'c': 'celsius',
    '°c': 'celsius',
    'celsius': 'celsius',
    'centigrade': 'celsius',
    'f': 'fahrenheit',
    '°f': 'fahrenheit',
    'fahrenheit': 'fahrenheit',
    'k': 'kelvin',
    'kelvin': 'kelvin',

    # --- Area ---
    'm²': 'square_meter',
    'sqm': 'square_meter',
    'square_meter': 'square_meter',
    'square_meters': 'square_meter',
    'sqft': 'square_foot',
    'square_foot': 'square_foot',
    'square_feet': 'square_foot',
    'acre': 'acre',
    'acres': 'acre',
    'hectare': 'hectare',
    'hectares': 'hectare',

    # --- Speed ---
    'm/s': 'meter_per_second',
    'mps': 'meter_per_second',
    'meter_per_second': 'meter_per_second',
    'km/h': 'kilometer_per_hour',
    'kph': 'kilometer_per_hour',
    'kmph': 'kilometer_per_hour',
    'kilometer_per_hour': 'kilometer_per_hour',
    'mph': 'mile_per_hour',
    'mile_per_hour': 'mile_per_hour',
    'kn': 'knot',
    'knot': 'knot',
    'knots': 'knot',

    # --- Energy ---
    'j': 'joule',
    'joule': 'joule',
    'joules': 'joule',
    'kj': 'kilojoule',
    'kilojoule': 'kilojoule',
    'kilojoules': 'kilojoule',
    'cal': 'calorie',
    'calorie': 'calorie',
    'calories': 'calorie',
    'kcal': 'kilocalorie',
    'kilocalorie': 'kilocalorie',
    'kilocalories': 'kilocalorie',
    'wh': 'watt_hour',
    'watt_hour': 'watt_hour',
    'watt_hours': 'watt_hour',
    'kwh': 'kilowatt_hour',
    'kilowatt_hour': 'kilowatt_hour',
    'kilowatt_hours': 'kilowatt_hour',

    # --- Power ---
    'w': 'watt',
    'watt': 'watt',
    'watts': 'watt',
    'kw': 'kilowatt',
    'kilowatt': 'kilowatt',
    'kilowatts': 'kilowatt',
    'mw': 'megawatt',
    'megawatt': 'megawatt',
    'megawatts': 'megawatt',
    'hp': 'horsepower',
    'horsepower': 'horsepower',

    # --- Pressure ---
    'pa': 'pascal',
    'pascal': 'pascal',
    'pascals': 'pascal',
    'kpa': 'kilopascal',
    'kilopascal': 'kilopascal',
    'kilopascals': 'kilopascal',
    'bar': 'bar',
    'bars': 'bar',
    'atm': 'atmosphere',
    'atmosphere': 'atmosphere',
    'atmospheres': 'atmosphere',
    'psi': 'pound_per_square_inch',
    'pound_per_square_inch': 'pound_per_square_inch',

    # --- Frequency ---
    'hz': 'hertz',
    'hertz': 'hertz',
    'khz': 'kilohertz',
    'kilohertz': 'kilohertz',
    'mhz': 'megahertz',
    'megahertz': 'megahertz',
    'ghz': 'gigahertz',
    'gigahertz': 'gigahertz',

    # --- Data ---
    'bit': 'bit',
    'bits': 'bit',
    'b': 'byte',
    'byte': 'byte',
    'bytes': 'byte',
    'kb': 'kilobyte',
    'kilobyte': 'kilobyte',
    'kilobytes': 'kilobyte',
    'mb': 'megabyte',
    'megabyte': 'megabyte',
    'megabytes': 'megabyte',
    'gb': 'gigabyte',
    'gigabyte': 'gigabyte',
    'gigabytes': 'gigabyte',
    'tb': 'terabyte',
    'terabyte': 'terabyte',
    'terabytes': 'terabyte',
    'pb': 'petabyte',
    'petabyte': 'petabyte',
    'petabytes': 'petabyte',

    # --- Electric / Misc ---
    'v': 'volt',
    'volt': 'volt',
    'volts': 'volt',
    'a': 'ampere',
    'amp': 'ampere',
    'amps': 'ampere',
    'ampere': 'ampere',
    'amperes': 'ampere',
    'ohm': 'ohm',
    'ohms': 'ohm',
    'Ω': 'ohm',
    'c': 'coulomb',
    'coulomb': 'coulomb',
    'coulombs': 'coulomb',
    'f': 'farad',
    'farad': 'farad',
    'farads': 'farad',
    't': 'tesla',
    'tesla': 'tesla',
    'teslas': 'tesla',

    # --- Currency (optional, for completeness) ---
    'usd': 'usd',
    'dollar': 'usd',
    'dollars': 'usd',
    '$': 'usd',
    'eur': 'euro',
    'euro': 'euro',
    'euros': 'euro',
    '£': 'pound_sterling',
    'gbp': 'pound_sterling',
    'pound_sterling': 'pound_sterling',
    '¥': 'yen',
    'jpy': 'yen',
    'yen': 'yen',
}
